force-app/main/default/objects/Custom_Event__c/Custom_Event__c.object-meta.xml
<CustomObject>
    <label>Custom Event</label>
    <nameField>
        <label>Custom Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Event__c/fields/Event_End__c.field-meta.xml
<CustomField>
    <fullName>Event_End__c</fullName>
    <description>The ending date and time of the event.</description>
    <label>Event End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/Event_Start__c.field-meta.xml
<CustomField>
    <fullName>Event_Start__c</fullName>
    <description>The initial date and time of the event.</description>
    <label>Event Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Custom_Event__c/fields/External_UUID__c.field-meta.xml
<CustomField>
    <fullName>External_UUID__c</fullName>
    <description>External ID used to reference an event when registering from external application.</description>
    <externalId>true</externalId>
    <label>External UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <description>A junction object that joins Contacts with Events</description>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>Reg-{00000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EventServiceLayerTests.cls
@isTest
private class EventServiceLayerTests {

    @isTest
    private static void testRegistrationRest(){

        Custom_Event__c evt = new Custom_Event__c(Name = 'My Event', Event_Start__c = System.now(), Event_End__c = System.now().addDays(1), External_UUID__c = 'e8b9e17d-a3c6-433c-a6d0-81c13ec9449b');
        insert evt;

        Map<String, Object> obj = new Map<String, Object>();
        obj.put('first', 'timmy');
        obj.put('last', 'test');
        obj.put('email', 'timmy@test.example');
        obj.put('eventUUID', 'e8b9e17d-a3c6-433c-a6d0-81c13ec9449b');

        // MyClass reqst=new MyClass();
        String JsonMsg=JSON.serialize(obj);
        Test.startTest();

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = '/services/apexrest/Registration/';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(JsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        EventRegistrationRest.postRegistration('timmy', 'test', 'timmy@test.example', 'e8b9e17d-a3c6-433c-a6d0-81c13ec9449b');

        //Could be more thorough here and create data with new method to test against, doing double post for brevity
        EventRegistrationRest.postRegistration('timmy', 'test', 'timmy@test.example', 'e8b9e17d-a3c6-433c-a6d0-81c13ec9449b');

        // update TestOpp;
        Test.stopTest();
        List<Event_Registration__c> registrations = [SELECT Id FROM Event_Registration__c];

        System.assertEquals(1, registrations.size(), 'Registration was not created');
    }
}